cafy_pdb
cafykit/cafy-pytest pull request #94
Opened 2023-04-19 15:58 UTC by pashupati123

1. Feature description and need for this PR
CafyPdb: Extending Pdb’s functionalities into our own custom debugger module

2. Proposed changes
added custom pdb class in lib in order to support CafyPdb

3. What type of testing has been done?

Test Log
Remote PDB connection

<img width="343" alt="1" src="https://user-images.githubusercontent.com/17371750/233132805-75d591c6-4ecd-4ee4-8003-0f15b891a91b.png">

<img width="1229" alt="2" src="https://user-images.githubusercontent.com/17371750/233132896-4e93ebf6-c0c7-44ae-b440-b14715bf2e6b.png">

<img width="1314" alt="3" src="https://user-images.githubusercontent.com/17371750/233132931-f647ffd4-23bb-427b-98f7-9b48f43f687a.png">

2023-05-12 17:11 UTC, nishantupadhyay123 requested changes

2023-05-12 17:11 UTC, nishantupadhyay123 commented on cafy_pytest/plugin.py
> +        end_port = 5999
this is not the right range

2023-06-06 05:42 UTC, nishantupadhyay123 commented
this is not capturing full output of shell or user action outputs.

2023-06-16 20:59 UTC, shreyashah approved these changes

2023-07-21 23:01 UTC, merged